### ISSUE TITLE
bug fix suggestion

### ISSUE THREAD

**Issue by sngyai** [otalk/jingle-session#5]
Sorry, but you should modify [JingleSession start](https://github.com/otalk/jingle-session/blob/master/index.js#L202) and add a random "id" attribute to it, otherwise ejabberd17.03 would response a bad-request: Missing attribute "id", as a result of ejabberd has been refactored since 17.01

**Comment by fippo** [comment]
@legastero can you take a look?

@sngyai can you show an example of the xml generated and the response please?

**Comment by sngyai** [comment]
I've uploaded xmpp log to my server, you can check it out by visiting [https://sngyai.com:5280/download/jingle_log.xml](https://sngyai.com:5280/download/jingle_log.xml), it is a part of them, since xmpp logs in chrome are too large.

**Comment by legastero** [comment]
Are you using this module through the `stanza.io` library, or using it directly?

Adding an `id` value here is doable without much of a downside, so I'll do that.

The original assumption was that it would be set by your XMPP library (since this module only emits JSON, not immediately sendable XML).

**Comment by sngyai** [comment]
Great! Thank you
